# Default values for redis-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env: 
  url: "localhost"
  redis_addr: "127.0.0.1"
  redis_password: "123456"
