apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    zookeeperurl: {{ .Values.env.url }}
    app: {{ template "zookeeper-exporter.name" . }}
    chart: {{ template "zookeeper-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "zookeeper-exporter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zookeeper-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        zookeeperurl: {{ .Values.env.url }}
        app: {{ template "zookeeper-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: carlpett/zookeeper_exporter:latest
        name: zookeeper-exporter
        command: ["/zookeeper_exporter", "-zookeeper", "{{ .Values.env.zookeeper_addr }}"]
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 9141
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zookeeperurl: {{ .Values.env.url }}
    app: {{ template "zookeeper-exporter.name" . }}
    chart: {{ template "zookeeper-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "zookeeper-exporter.fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'
    #prometheus.io/path: '/metrics'
    #prometheus.io/port: '8080'
spec:
  ports:
  - name: http
    port: 9141
    targetPort: http
  selector:
    app: {{ template "zookeeper-exporter.name" . }}
    release: {{ .Release.Name }}
